// <auto-generated />
namespace App_Tutorias_Turing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migracionInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracionInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202410270131141_migracionInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
